SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA6FA1B8}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7D8ED340882}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{5C62F7D8ED9E5390}" {
     m_bEnabled 0
    }
   }
  }
 }
}