SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A1CE9B9648C43EA}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6A1CE9B9648C43D8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648C43C6}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648C43C4}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648C43C5}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CB1C8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CB1CE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CB1CD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CB1CC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CB1C3}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CB1C2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CFACB}" {
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CFAC9}" {
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CFABF}" {
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6A1CE9B9648CFABC}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CFAA2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CFAA3}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CFAA0}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648CFAA1}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648D1BDC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648D1BDB}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A1CE9B9648D1BDA}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6A1CE9B9648D1BD9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648D1BD8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648D1BD2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1CE9B9648D1BD1}" {
     m_bEnabled 0
    }
   }
  }
 }
}