SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A1B315552C92880}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6A1B315552C9288B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C92889}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C92876}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C92877}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C92874}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C92875}" {
    }
    SCR_EntityCatalogEntry "{6A1B315552C92872}" {
    }
    SCR_EntityCatalogEntry "{6A1B315552C92873}" {
    }
    SCR_EntityCatalogEntry "{6A1B315552C92870}" {
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A1B315552C92871}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6A1B315552C9287E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C9287F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C92866}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6A1B315552C92867}" {
     m_bEnabled 0
    }
   }
  }
 }
}