SCR_EditorManagerCore {
 m_ModePrefabs {
  SCR_EditorModePrefab "{6A236469E60EEABE}" {
   m_Mode GRAD_BC_SPECTATE
   m_Prefab "{1FDB8868AB2119E4}Prefabs/Editor/Modes/EditorModeBCSpectate.et"
   m_Flags DEFAULT
   m_ModeUIInfo SCR_EditorModeUIInfo "{6A236469E60EEABF}" {
    Name "Spectate"
    Description "Return to spectator"
    Icon "{1CD65C97061661F6}UI/Textures/Editor/Logos/Editor-Logo.imageset"
    IconSetName "Logo_Editor"
    m_ModeColor 0.017 0.198 0.048 1
    m_iOrder 15
   }
  }
 }
}
